/* COPYING A TABLE WITH REFERENCE */

CREATE TABLE "PKALLEPALLI"."officeInfo" LIKE "hd"."DDB_HDC_OFFICEINFO";

CREATE TABLE "PKALLEPALLI"."officeInfo" LIKE "hd"."DDB_HDC_OFFICEINFO" WITH DATA;

CREATE COLUMN TABLE "PKALLEPALLI"."officeId" AS (SELECT "RSCDB" FROM "hd"."DDB_HDC_OFFICEINFO") ;


/* important catalog object tables */

SELECT * FROM "SCHEMAS";

SELECT * FROM "TABLES" WHERE "SCHEMA_NAME" = 'hd';

SELECT * FROM "TABLE_COLUMNS" WHERE "SCHEMA_NAME" = 'hd' AND "TABLE_NAME" = 'DDB_HDC_OFFICEINFO';

SELECT * FROM "SEQUENCES" WHERE "SCHEMA_NAME" = 'hd';

SELECT * FROM "TRIGGERS" WHERE "SCHEMA_NAME" = 'hd';

SELECT * FROM "INDEXES" WHERE "SCHEMA_NAME" = 'hd' AND "TABLE_NAME" = 'DDB_HDC_OFFICEINFO';

SELECT * FROM "PROCEDURES" WHERE "SCHEMA_NAME" = 'bi' ;

SELECT * FROM "FUNCTIONS" WHERE "SCHEMA_NAME" = 'bi' ;

SELECT * FROM "VIEWS" WHERE "SCHEMA_NAME" = '_SYS_BIC' AND "VIEW_TYPE" = 'CALC' ;
