



---- SINGLE LEVEL TABLE PARTITIONING ----

-- HASH PARTITIONING
ALTER TABLE "ECC"."SAPHANADB_VBAP" 
PARTITION BY 
	HASH ("VBELN", "POSNR") PARTITIONS 4
	;

ALTER TABLE "ECC"."SAPHANADB_VBAP" 
PARTITION BY 
	HASH ("VBELN",, "POSNR") PARTITIONS GET_NUM_SERVERS()
	;


-- ROUND ROBIN
ALTER TABLE "ECC"."SAPHANADB_VBAP" 
PARTITION BY 
	ROUNDROBIN PARTITIONS 4
	;
ALTER TABLE "ECC"."SAPHANADB_VBAP" 
PARTITION BY 
	ROUNDROBIN PARTITIONS GET_NUM_SERVERS()
	;

-- RANGE PARTITIONING

ALTER TABLE "ECC"."SAPHANADB_VBAK" 
PARTITION BY
		
		RANGE ("ERDAT")
			(PARTITION '20170101' <= VALUES < '20180101', 
			 PARTITION '20160101' <= VALUES < '20170101',
			 PARTITION OTHERS) 
			 ;

---- MULTI LEVEL TABLE PARTITIONING  -----

----MULTI LEVEL HASH - RANGE PARTITIONING -----


ALTER TABLE "ECC"."SAPHANADB_VBAK" 

PARTITION BY
		HASH ("VBELN") PARTITIONS GET_NUM_SERVERS(), 
		
		RANGE ("ERDAT")
			(PARTITION '20170101' <= VALUES < '20180101', 
			 PARTITION '20160101' <= VALUES < '20170101',
			 PARTITION OTHERS) 
			 
		;
		
--- ADDING ADDITIONAL RANGE PARTITIONS ---
		
ALTER TABLE "ECC"."SAPHANADB_VBAK"  ADD PARTITION '20160101' <= VALUES < '20170101';	 


-- MERGE Partitions -----

	-- Will Merge partitions into one loike non-partitioned table.

ALTER TABLE "ECC"."SAPHANADB_VBAK"  MERGE PARTITIONS 



---- Moving Partition Between Stores ----


	
--- DROPPING PARTITIONS ----- 

--!!!!!! CAUTION - DROPPING PARTITION ACTUALLY DELTES DATA IN THE TABLE !!!!!!
		
ALTER TABLE "ECC"."SAPHANADB_VBAK"  DROP PARTITION '20160101' <= VALUES < '20170101';
			
ALTER TABLE "ECC"."SAPHANADB_VBAK"  DROP PARTITION OTHERS;