-- list of tables
SELECT *
FROM "SYS"."TABLES"
WHERE "SCHEMA_NAME" = 'THS_ECC';


-- List of Objects by Package ID
select 
"PACKAGE_ID",
"OBJECT_NAME",
"OBJECT_SUFFIX"
 from "_SYS_REPO"."ACTIVE_OBJECT"
 WHERE "PACKAGE_ID" LIKE 'hd.bi.kpi.hygienist.dashboard'
 order by lower("OBJECT_NAME")


-- list of objects in the change list
SELECT *
FROM "_SYS_REPO"."CHANGE_ENTRIES"
WHERE "PACKAGE_ID" LIKE 'ths.sd.sap%'
ORDER BY "CHANGE_NUMBER"
	,"PACKAGE_ID"
	,"OBJECT_NAME";


--	Changelists

	SELECT "SRC_SYSTEM"
	,"CHANGE_NUMBER"
	,"STATUS"
	,"DESCRIPTION"
	,"CREATED_AT"
	,"CREATED_BY"
	,"RELEASED_AT"
	,"RELEASED_BY"
FROM "_SYS_REPO"."CHANGES"
WHERE "RELEASED_BY" IN (
		'KALLEPAP'
		,'VARADHAS'
		)
ORDER BY "CHANGE_NUMBER"

--To Find Objects with Deletion Indicator in Change List

SELECT DISTINCT A."SRC_SYSTEM"
	,A."CHANGE_NUMBER"
	,A."PACKAGE_ID"
	,A."OBJECT_NAME"
	,A."OBJECT_SUFFIX"
	,B."IS_DELETION"
FROM "_SYS_REPO"."CHANGE_ENTRIES" A
INNER JOIN "_SYS_REPO"."OBJECT_HISTORY" B ON A."PACKAGE_ID" = B."PACKAGE_ID"
	AND A."OBJECT_NAME" = B."OBJECT_NAME"
	AND A."OBJECT_SUFFIX" = B."OBJECT_SUFFIX"
WHERE A."CHANGE_NUMBER" = 3292

-- change list cross walk in target system

SELECT "SRC_SYSTEM"
	,"CHANGE_NUMBER"
	,"STATUS"
	,"DESCRIPTION"
	,"CREATED_AT"
	,"CREATED_BY"
	,"RELEASED_AT"
	,"RELEASED_BY"
FROM "_SYS_REPO"."CHANGES"
ORDER BY "RELEASED_AT"

-- list of active objects
SELECT "PACKAGE_ID"
	,"OBJECT_NAME"
	,"OBJECT_SUFFIX"
	,"VERSION_ID"
	,"ACTIVATED_AT"
	,"ACTIVATED_BY"
	,"RELEASED_AT"
FROM "_SYS_REPO"."ACTIVE_OBJECT"
WHERE "PACKAGE_ID" LIKE 'ths.sd.sap%'


-- Get All Objects by Package and Change Number And released Status
SELECT A."SRC_SYSTEM",
	A."PACKAGE_ID",
	A."OBJECT_NAME",
	A."OBJECT_SUFFIX",
	A."CHANGE_NUMBER",
	B."STATUS",
	B."RELEASED_AT"
FROM "_SYS_REPO"."CHANGE_ENTRIES" AS A LEFT OUTER JOIN "_SYS_REPO"."CHANGES" AS B
		ON A."SRC_SYSTEM" = B."SRC_SYSTEM" 
			AND  A."CHANGE_NUMBER" = B."CHANGE_NUMBER"
WHERE A."PACKAGE_ID" LIKE 'hd.bi.db.func%' AND B."RELEASED_AT" IS NULL
ORDER BY "CHANGE_NUMBER"
	,"PACKAGE_ID"
	,"OBJECT_NAME";
	
	


-- Get All Objects by package And Change Number with Deletion Status AND Released Status

SELECT A."SRC_SYSTEM",
	A."PACKAGE_ID",
	A."OBJECT_NAME",
	A."OBJECT_SUFFIX",
	A."CHANGE_NUMBER",
	C."STATUS",
	C."RELEASED_AT",
	SUM(B."IS_DELETION")
FROM "_SYS_REPO"."CHANGE_ENTRIES" AS A  LEFT OUTER JOIN "_SYS_REPO"."OBJECT_HISTORY" AS B 	
	ON A."PACKAGE_ID" = B."PACKAGE_ID"
			AND A."OBJECT_NAME" = B."OBJECT_NAME"
			AND A."OBJECT_SUFFIX" = B."OBJECT_SUFFIX"
		LEFT OUTER JOIN "_SYS_REPO"."CHANGES" C
			ON A."SRC_SYSTEM" =  C."SRC_SYSTEM"
			AND A."CHANGE_NUMBER" = C."CHANGE_NUMBER"
WHERE A."PACKAGE_ID" LIKE 'hd.bi.db.ddl%' AND C."RELEASED_AT" IS NULL
GROUP BY  A."SRC_SYSTEM",
	A."PACKAGE_ID",
	A."OBJECT_NAME",
	A."OBJECT_SUFFIX",
	A."CHANGE_NUMBER",
	C."STATUS",
	C."RELEASED_AT"
ORDER BY
	A."PACKAGE_ID"
	,A."OBJECT_NAME"
	,A."OBJECT_SUFFIX"
	,A."CHANGE_NUMBER";