

--- User Creation

CREATE USER PKALLEPALLI PASSWORD SAP123;
CREATE USER PKALLEPALLI PASSWORD SAP123 FORCE_FIRST_PASSWORD_CHANGE;
CREATE USER PKALLEPALLI PASSWORD SAP123 NO FORCE_FIRST_PASSWORD_CHANGE;
CREATE USER PKALLEPALLI PASSWORD SAP123  FORCE_FIRST_PASSWORD_CHANGE SET PARAMETER CLIENT = '100', EMAIL = 'pkallepalli@heartland.com' -- <other user paramters include, LOCALE, PROIORIY, TIME ZONE, STATEMENT MEMORY LIMIT>
CREATE RESTRICTED USER PKALLEPALLI PASSWORD SAP123;

CREATE RESTRICTED USER TEST_SCRIPT PASSWORD Password1 
	WITH IDENTITY 'pkallepalli@heartland.com' FOR SAML PROVIDER TEST_HEARTLAND_DENTAL_Q_US2_SAPANALYTICS_CLOUD_
	SET PARAMETER 
		EMAIL ADDRESS = 'pkallepalli@heartland.com'
		, CLIENT = '100'
		, LOCALE = 'EN'
		, TIMEZONE = 'EST'
		--, PRIORITY = 
		--, STATEMENT MEMORY LIMIT = 

/*		;
 EXECUTE IMMEDIATE 
 'CREATE RESTRICTED USER ' 
 	|| :vUserName || ' PASSWORD ' || :vPassword || 
	 ' NO FORCE_FIRST_PASSWORD_CHANGE ' || 
	 ' VALID FROM NOW UNTIL FOREVER';
*/
-- ALTER USER

ALTER USER PKALLEPALLI DEACTIVATE;
ALTER USER PKALLEPALLI ACTIVATE;
ALTER USER PKALLEPALLI RESET CONNECT ATTEMPTS; 
	NOTE: RESETS THE NUMBER OF INAVALID CONNECT ATTEMPTS TO ZERO, ALLOWING THE USER TO CONNECT IMMEDIATELY.
ALTER USER PKALLEPALLI DROP CONNECT ATTEMPTS;
	NOTE: DROPS OLD INFORMATION ABOUT INVALID CONNECT ATTEMPTS RECORDED, IT DOES NOT RESET THE COUNT OF CURRENTLY RECORDED FAILED ATTEMPTS, SO DOES NOT ALLOW TO CONNECT IMMEDIALTELY.
ALTER USER PKALLEPALLI ENABLE PASSWORD LIFETIME;
ALTER USER PKALLEPALLI DISABLE PASSWORD LIFETIME;
ALTER USER PKALLEPALLI ENABLE SAML;
ALTER USER PKALLEPALLI DISABLE SAML;

ALTER USER PKALLEPALLI ADD IDENTITY <EXTERNAL_IDENTITY> FOR SAML PROVIDER <IDENTITY_PROVIDER_NAME>;
ALTER USER PKALLEPALLI ADD IDENTITY ANY FOR SAML PROVIDER <IDENTITY_PROVIDER_NAME>;


-- ASSIGNING DESIGN TIME ROLES <CREATED USING .HDBROLE> TO A PRINCIPLE:
CALL GRANT_ACTIVATED_ROLE ('hd.sec.common::basicRole','PKALLEPALLI');
CALL GRANT_ACTIVATED_ROLE ('hd.sec.common.dentrix::hygienistEndUser','PKALLEPALLI');



--INFO ABOUT USER

	-- FOR INVALID CONNECT ATTEMPTS:
		
		SELECT *
		FROM SYS.INVALID_CONNECT_ATTEMPTS
		WHERE USER_NAME = ‘PKALLEPALLI’
		;
	
	-- USER ATTRIBUTES:

		SELECT *
		FROM SYS.USERS
		WHERE USER_NAME = ‘PKALLEPALLI’
		;
		
	-- USER PARAMETERS:

		SELECT *
		FROM USER_PARAMETERS
		WHERE USER_NAME = ‘PKALLEPALLI’
		;
		
	-- SAML USER MAPPINGS

		SELECT *
		FROM SAML_USER_MAPPINGS
		WHERE USER_NAME = ‘PKALLEPALLI’
		;
		
	-- ROLES OF CURRENT USER

		SELECT *
		FROM EFFECTIVE_ROLES
		WHERE USER_NAME = ‘PKALLEPALLI’
		;

	-- PREVILEGES OF CURRENT USER

		SELECT *
		FROM EFFECTIVE_PRIVILEGES
		WHERE USER_NAME = ‘PKALLEPALLI’
		;


-- calculation views with analytical privileges SELECT

SELECT  "USER_NAME", "SCHEMA_NAME", "VIEW_NAME", "ANALYTICAL_PRIVILEGE_NEEDED"
FROM "SYS"."ACCESSIBLE_VIEWS"
WHERE "USER_NAME" = 'KALLEPAP' AND "ANALYTICAL_PRIVILEGE_NEEDED" = 'TRUE' AND "VIEW_NAME" LIKE 'ths.copa%'
ORDER BY "VIEW_NAME"

--
-- fo find the external identity user name assigned for SAML --
SELECT "USER_NAME", "SAML_PROVIDER_NAME", "EXTERNAL_IDENTITY"
FROM "SYS"."SAML_USER_MAPPINGS" ;


-- to find what is the session client for the user --
SELECT "USER_NAME", "PARAMETER", "VALUE"
FROM "SYS"."USER_PARAMETERS"
WHERE "PARAMETER" = 'CLIENT'



